env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - import
rules: 
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 0
  import/export: 2
  react/react-in-jsx-scope: 0
  no-unused-vars: 0
  react/prop-types: 0
  import/prefer-default-export: 0